spring:
  application:
    name: scuba-logging-service
  cloud:
    kubernetes:
      config:
        enabled: true
        reload:
          enabled: true
        name: scuba-logging-service # rename configMap to scuba-logging-service-config, might require sources
      secrets:
        paths:
        - /etc/secrets/hello-secret
  datasource:
    # driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/fish
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    ddl-auto: update



test:
  hello: local
