apiVersion: apps/v1
kind: Deployment
metadata:
  name: scuba-logging-service
spec:
  selector:
    matchLabels:
      app: scuba-logging-service
  template:
    metadata:
      labels:
        app: scuba-logging-service
    spec:
      serviceAccountName: scuba-logging-service-account
      containers:
        - name: scuba-logging-service
          image: denizcankurtaran006/scuba-logging-service:1.0.3
          ports:
            - containerPort: 8080
          env:
            - name: ENV_HELLO
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: foo