apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-role-binding
subjects:
- kind: ServiceAccount
  name: scuba-logging-service-account
roleRef:
  kind: Role
  name: configmap-role
  apiGroup: rbac.authorization.k8s.io